name: flutter_3d_measure
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vector_math: ^2.2.0
  flutter_native_splash: ^2.4.7
  path_provider: ^2.1.5
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

# flutter_launcher_icons:
#   ios: true
#   image_path: "assets/icon.png"

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/icon.png